language: php
dist: bionic

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer config -g  discard-changes 1 # because we used travis cache and, sometimes, packages change
  - mkdir -p ./build/coverage
  - mkdir -p ./build/logs
  - composer install --prefer-source

script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
       ./vendor/bin/phpunit -v --configuration tests/travis/$DB.travis.xml --coverage-php build/coverage/coverage-$DB-$TRAVIS_PHP_VERSION-2.7.cov
    else
       ./vendor/bin/phpunit -v --configuration tests/travis/$DB.travis.xml
    fi
  # Code shall respect rules
  - composer check-quality-code

after_script:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
       ./vendor/bin/phpcov merge --clover build/logs/clover.xml build/coverage
       ./vendor/bin/php-coveralls -vvv --exclude-no-stmt
    fi

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_WEBHOOK

jobs:
  include:
    #MySQL 8 PHP 8.1
    - stage: PHP8
      name: MySQL8
      php: 8.1
      env: DB=mysql.docker MYSQL_VERSION=8.0
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    #MySQLi 8 PHP 8.1
    - stage: PHP8
      name: MySQLi8
      php: 8.1
      env: DB=mysqli.docker MYSQL_VERSION=8.0
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mysql-8.0.sh
    #PostgreSQL11 PHP 8.1 Postgis 2.5
    - stage: PHP8
      name: PostgreSQL11 Postgis 2.5
      php: 8.1
      env: DB=pgsql POSTGRESQL_VERSION=11.0
      sudo: required
      addons:
        postgresql: "11"
        apt:
          packages:
            - postgis
            - postgresql-11-postgis-2.5
